language: php
php:
    - 5.5
before_install:
    - wget https://phar.phpunit.de/phpunit.phar
    - chmod +x phpunit.phar
    - sudo mv phpunit.phar /usr/local/bin/phpunit
script:
    - phpunit *Test.php --verbose
notifications:
    email: false
